version: '3.8'


services:
  mongodb:
    container_name: mongo_db
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
      - ./environment/mongo/init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_INITDB_DATABASE=test
    restart: unless-stopped

volumes:
  mongo: